export const ENTITIES = [
  ['financialParties', 'financial_parties'],
  ['institutions', 'institutions'],
  ['instruments', 'instruments'],
  ['accounts', 'logical_accounts'],
  ['sourceBindings', 'account_source_bindings'],
  ['balances', 'balance_observations'],
  ['positions', 'position_observations'],
  ['prices', 'price_observations'],
  ['rates', 'exchange_rates'],
  ['ufValues', 'uf_values'],
  ['ownershipDecisions', 'ownership_decisions'],
  ['inclusionDecisions', 'inclusion_decisions'],
  ['manualAssets', 'manual_assets'],
  ['liabilities', 'liabilities'],
  ['obligations', 'obligations'],
  ['obligationEvents', 'obligation_events'],
  ['duplicates', 'duplicate_candidates'],
  ['reviewTasks', 'review_tasks'],
  ['resolutions', 'resolution_decisions'],
] as const;
